### ISSUE TITLE
[ask] tabel fisik sqlite

### ISSUE THREAD

**Issue by atmanegara** [dyazincahya/sqlite-helper-nativescript#1]
mas kan ada create database 
const sqlite = openOrCreate("dbname.db");

itu ada tabel fisiknya ga ke create dalam projectnya, 
kalau ada itu letaknya dimana?
kalau ga ada, apa bisa di akses via terminal / cmd?

**Comment by dyazincahya** [comment]
Letakan database fisik di dalam folder app
"project/app/dbname.db"


Contoh kode untuk membuat tabelnya bisa lihat disini, lihat pada function init__table() :
https://github.com/x-labs-86/buku-kasbon/blob/main/app%2Fglobal_helper.js


Lengkapnya bisa lihat di projek saya yang satu ini : https://github.com/x-labs-86/buku-kasbon
